### ISSUE TITLE
Follow up on all links to individuals provided during Tech Talk

### ISSUE THREAD

**Issue by ChristinaLast** [ChristinaLast/open-climate-data-science-unconference#3]
# Christina’s SSI Fellowship
###### tags: `SSI Fellowship` `Personal` `02/22`
My `SoftwareSaved` fellowship will aim to address environmental sustainability alongside software sustainability. To do this, I intend to run a 3-day a collaborative “global eco hack” where everyone from 16-year-olds to PhD students to corporate research labs can help develop software to solve ecological challenges. 

###### <span style="font-family:Courier; font-size:4em;">Quick Links</span>
- 🎁 [Slides](https://docs.google.com/presentation/d/1xNJU4TIFVRaJB8xtDxJxT3aBCDD9nfOBjBG7b6Hi-sE/edit?usp=sharing)
- 📝 [Project Board](https://github.com/users/ChristinaLast/projects/2)
- 👩🏻‍💻 [Github Repo](https://github.com/ChristinaLast/open-climate-data-science-unconference)

###### <span style="font-family:Courier; font-size:4em;">Questions</span>
* Learnings from previous hybrid event?
	* DSGs have been running remotely for ~2 years. Jules and Daisy might have some useful experience running hack-style events.
	   * Jules Manser and Daisy Parry
	   * Also see Data Study Group guidance in general (e.g. for challenge owners, PIs, participants), some available here: https://www.turing.ac.uk/collaborate-turing/data-study-groups
	   * DSG - new job for a week, rather than 3 days.
    * Met office climate data science challenge
    * https://www.turing.ac.uk/events/webinar-edge-computing-earth-observation was an even we ran early on (March 2020!): the events team were incredibly helpful in making this work, and they've obviously had a lot of experience since.  It was 'hybrid', although there were only a few of us in the office at the time.
* Who to connect with for challenge ideas?
    * [MET Office Climate Data Challenge](https://www.metoffice.gov.uk/weather/climate/cop/climate-data-challenge)
    * Environment & Sustainability Interest Group
        * Networking event in manchester in March (in-person) ask Scott about this
        * Gavin Shaddick and WHO 
    * Data Science for Science
    * Scivision project (has REG involvement, Ed & Oliver)
    * via Jon C: https://4c.cst.cam.ac.uk/
- Areille is PM for a ASG climate/sustainability project
- [Environmental and Sustainability for NGO's](https://www.turing.ac.uk/opportunities-turing/environmental-charities-ngos)
- DataKind? https://www.datakind.org/
    - Laura Carter
* How to reach out to Turing’s network?
   * Event early March - looking for volunteers https://www.turing.ac.uk/opportunities-turing/environmental-charities-ngos
   * Environment & Sustainability Interest Group
   * In person events
       * Events team - booking form to request
       * Hub and spoke, microgrants to meet together.
       * Sophia ran hackathon with MIT reality, media lab in VR
- SSI 
    - The SSI also has a connection with the EEI (environment and something institute) at the University of Hull. The EEI do a lot of outreach in local schools
* AI UK
* Learning as a core theme of the event?

#### Tasks
- [ ] Share blurb with Malvika for open geospatial data 
    - [ ] Reply to Arielle laura carter with intro
- [ ] Reach out to Scott Hoskin about networking and 
- [ ] Reach out to BAS SSI fellow to see what he is thinking of
